server:
  port: 8082
spring:
  application:
    name: "solicitud"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: solicitudes
    schema: public
    username: duvan
    password: duvan
security:
  jwt:
    secret: "hjsdf7y32hjk23hjk23hjkh23kjh23kjh23kjh23kjh23kjh23kjh23"
